# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='image',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
